version: '2'

services:
  mariadb:
    image: docker.io/bitnami/mariadb:11.2
    ports:
      - '3306:3306'
    expose:
      - '3306'
    env_file:
      - ".env"
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
  myapp:
    tty: true
    image: docker.io/bitnami/laravel:10
    labels:
      kompose.service.type: nodeport
    ports:
      - '8000:8000'
    env_file:
      - ".env"
    environment:
      - DB_HOST=mariadb
      - DB_PORT=3306
      - DB_USERNAME=${MARIADB_USER}
      - DB_DATABASE=${MARIADB_DATABASE}
      - DB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - './my-project:/app'
    depends_on:
      - mariadb