<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Producto;

class ProductoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $productos = [
            [
                'nombre' => 'Televisor Smart 50"',
                'descripcion' => 'Televisor con resolución 4K y conexión a internet',
                'precio' => 599.99,
                'unidades' => 20,
                'imagen' => 'televisor.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Lavadora 8Kg',
                'descripcion' => 'Lavadora de carga frontal, eficiencia energética A++',
                'precio' => 349.99,
                'unidades' => 15,
                'imagen' => 'lavadora.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Cafetera Express',
                'descripcion' => 'Cafetera Express con 15 bares de presión',
                'precio' => 89.99,
                'unidades' => 30,
                'imagen' => 'cafetera.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Aceite de oliva virgen extra 1L',
                'descripcion' => 'Aceite de oliva de primera presión en frío',
                'precio' => 7.99,
                'unidades' => 200,
                'imagen' => 'aceite.jpg',
                'categoria_id' => '11',
            ],
            [
                'nombre' => 'Licuadora de Frutas y Verduras',
                'descripcion' => 'Licuadora con potencia de 800W',
                'precio' => 45.99,
                'unidades' => 25,
                'imagen' => 'licuadora.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Arroz Basmati 1Kg',
                'descripcion' => 'Arroz Basmati de grano largo',
                'precio' => 3.99,
                'unidades' => 150,
                'imagen' => 'arroz.jpg',
                'categoria_id' => '11',
            ],
            [
                'nombre' => 'Tostadora de Pan',
                'descripcion' => 'Tostadora con capacidad para dos rebanadas',
                'precio' => 22.99,
                'unidades' => 30,
                'imagen' => 'tostadora.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Pasta Integral 500g',
                'descripcion' => 'Pasta integral de trigo duro',
                'precio' => 1.99,
                'unidades' => 200,
                'imagen' => 'pasta.jpg',
                'categoria_id' => '11',
            ],
            [
                'nombre' => 'Batidora de Mano',
                'descripcion' => 'Batidora de mano con potencia de 600W',
                'precio' => 29.99,
                'unidades' => 20,
                'imagen' => 'batidora.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Atún en Aceite 160g',
                'descripcion' => 'Lata de atún en aceite de oliva',
                'precio' =>1.49,
                'unidades' => 100,
                'imagen' => 'atun.jpg',
                'categoria_id' => '11',
            ],
            [
                'nombre' => 'Robot de Cocina Multifunción',
                'descripcion' => 'Robot de cocina con múltiples funciones: cocinar, triturar, batir, y más',
                'precio' => 249.99,
                'unidades' => 10,
                'imagen' => 'robot_cocina.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Colchón Viscoelástico 150x200cm',
                'descripcion' => 'Colchón viscoelástico con sistema de ventilación y funda lavable',
                'precio' => 399.99,
                'unidades' => 20,
                'imagen' => 'colchon.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Gafas de Sol Polarizadas',
                'descripcion' => 'Gafas de sol polarizadas con protección UV400',
                'precio' => 59.99,
                'unidades' => 30,
                'imagen' => 'gafas_sol.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Manta Eléctrica',
                'descripcion' => 'Manta eléctrica con varias temperaturas y temporizador',
                'precio' => 49.99,
                'unidades' => 25,
                'imagen' => 'manta.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Perfume para Hombre 100ml',
                'descripcion' => 'Fragancia masculina con notas amaderadas y cítricas',
                'precio' => 79.99,
                'unidades' => 40,
                'imagen' => 'perfume_hombre.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Mochila Portátil 15.6"',
                'descripcion' => 'Mochila para portátil de hasta 15.6" con compartimentos acolchados',
                'precio' => 39.99,
                'unidades' => 50,
                'imagen' => 'mochila.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Zapatillas Deportivas Mujer',
                'descripcion' => 'Zapatillas deportivas para mujer, ideales para correr o entrenar',
                'precio' => 69.99,
                'unidades' => 35,
                'imagen' => 'zapatillas_mujer.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Máquina de Afeitar Eléctrica',
                'descripcion' => 'Máquina de afeitar eléctrica con cuchillas autoafilables',
                'precio' => 89.99,
                'unidades' => 20,
                'imagen' => 'afeitadora.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Teclado Mecánico para Gaming',
                'descripcion' => 'Teclado mecánico para gaming con retroiluminación LED',
                'precio' => 129.99,
                'unidades' => 15,
                'imagen' => 'teclado_gaming.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Cámara de Seguridad WiFi',
                'descripcion' => 'Cámara de seguridad con conexión WiFi y visión nocturna',
                'precio' => 79.99,
                'unidades' => 25,
                'imagen' => 'camara_seguridad.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Secadora de Ropa 10Kg',
                'descripcion' => 'Secadora de ropa de carga frontal con capacidad para 10kg',
                'precio' => 499.99,
                'unidades' => 10,
                'imagen' => 'secadora.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Sartén Antiadherente 24cm',
                'descripcion' => 'Sartén antiadherente con recubrimiento cerámico de 24cm',
                'precio' => 29.99,
                'unidades' => 50,
                'imagen' => 'sarten.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Juego de Cuchillos de Cocina',
                'descripcion' => 'Set de 5 cuchillos de cocina de acero inoxidable con base de madera',
                'precio' => 39.99,
                'unidades' => 40,
                'imagen' => 'cuchillos.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Vino Tinto Reserva 750ml',
                'descripcion' => 'Botella de vino tinto reserva de 750ml',
                'precio' => 19.99,
                'unidades' => 60,
                'imagen' => 'vino.jpg',
                'categoria_id' => '11',
            ], [
                'nombre' => 'Aspiradora sin Bolsa',
                'descripcion' => 'Aspiradora sin bolsa con tecnología ciclónica y filtro HEPA',
                'precio' => 149.99,
                'unidades' => 20,
                'imagen' => 'aspiradora.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Smartwatch Fitness',
                'descripcion' => 'Smartwatch diseñado para fitness con monitor de frecuencia cardíaca y GPS integrado',
                'precio' => 129.99,
                'unidades' => 30,
                'imagen' => 'smartwatch.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Maleta de Viaje Grande',
                'descripcion' => 'Maleta de viaje grande con ruedas multidireccionales y cerradura TSA',
                'precio' => 89.99,
                'unidades' => 25,
                'imagen' => 'maleta.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Cafetera de Goteo Programable',
                'descripcion' => 'Cafetera de goteo con temporizador programable y jarra térmica',
                'precio' => 59.99,
                'unidades' => 15,
                'imagen' => 'cafetera_goteo.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Monitor Curvo 27"',
                'descripcion' => 'Monitor curvo de 27" con resolución QHD y frecuencia de actualización de 144Hz',
                'precio' => 349.99,
                'unidades' => 10,
                'imagen' => 'monitor_curvo.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Batería Externa Portátil 20000mAh',
                'descripcion' => 'Batería externa portátil de 20000mAh con carga rápida',
                'precio' => 39.99,
                'unidades' => 40,
                'imagen' => 'bateria_portatil.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Set de Té Verde',
                'descripcion' => 'Set de té verde con diferentes variedades y accesorios para prepararlo',
                'precio' => 24.99,
                'unidades' => 50,
                'imagen' => 'te_verde.jpg',
                'categoria_id' => '11',
            ],
            [
                'nombre' => 'Reloj de Pared Moderno',
                'descripcion' => 'Reloj de pared moderno con diseño minimalista',
                'precio' => 19.99,
                'unidades' => 60,
                'imagen' => 'reloj_pared.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Funda Nórdica 150x200cm',
                'descripcion' => 'Funda nórdica para cama de 150x200cm con diseño reversible',
                'precio' => 29.99,
                'unidades' => 30,
                'imagen' => 'funda_nordica.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Altavoz Bluetooth Impermeable',
                'descripcion' => 'Altavoz Bluetooth impermeable ideal para uso en exteriores',
                'precio' => 69.99,
                'unidades' => 25,
                'imagen' => 'altavoz_bluetooth.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Cepillo de Dientes Eléctrico',
                'descripcion' => 'Cepillo de dientes eléctrico recargable con sensor de presión',
                'precio' => 49.99,
                'unidades' => 35,
                'imagen' => 'cepillo_dientes.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Mesa de Centro de Cristal',
                'descripcion' => 'Mesa de centro de cristal templado con estructura metálica',
                'precio' => 129.99,
                'unidades' => 20,
                'imagen' => 'mesa_centro.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Lámpara de Pie LED',
                'descripcion' => 'Lámpara de pie LED con regulador de intensidad y control remoto',
                'precio' => 79.99,
                'unidades' => 30,
                'imagen' => 'lampara_pie.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Ebook Reader 6"',
                'descripcion' => 'Ebook Reader de 6" con pantalla táctil antirreflejos y luz integrada',
                'precio' => 99.99,
                'unidades' => 40,
                'imagen' => 'ebook_reader.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Set de Brochas de Maquillaje',
                'descripcion' => 'Set de brochas de maquillaje profesionales con estuche de viaje',
                'precio' => 24.99,
                'unidades' => 50,
                'imagen' => 'brochas_maquillaje.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Soporte para Portátil Ajustable',
                'descripcion' => 'Soporte para portátil ajustable con diseño ergonómico',
                'precio' => 34.99,
                'unidades' => 40,
                'imagen' => 'soporte_portatil.jpg',
                'categoria_id' => '1',
            ],
            [
                'nombre' => 'Báscula Digital de Cocina',
                'descripcion' => 'Báscula digital de cocina con pantalla LCD y función de tara',
                'precio' => 19.99,
                'unidades' => 50,
                'imagen' => 'bascula_cocina.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Pelota de Fútbol Adidas',
                'descripcion' => 'Pelota de fútbol oficial de Adidas, tamaño 5',
                'precio' => 29.99,
                'unidades' => 30,
                'imagen' => 'pelota_futbol.jpg',
                'categoria_id' => '3',
            ],
            [
                'nombre' => 'Silla Ergonómica de Oficina',
                'descripcion' => 'Silla ergonómica de oficina con soporte lumbar ajustable',
                'precio' => 199.99,
                'unidades' => 20,
                'imagen' => 'silla_oficina.jpg',
                'categoria_id' => '2',
            ],
            [
                'nombre' => 'Gorra de Béisbol',
                'descripcion' => 'Gorra de béisbol unisex con cierre ajustable',
                'precio' => 14.99,
                'unidades' => 60,
                'imagen' => 'gorra.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Mochila de Senderismo 40L',
                'descripcion' => 'Mochila de senderismo de 40 litros con cubierta para la lluvia',
                'precio' => 49.99,
                'unidades' => 30,
                'imagen' => 'mochila_senderismo.jpg',
                'categoria_id' => '4',
            ],
            [
                'nombre' => 'Balón de Baloncesto Spalding',
                'descripcion' => 'Balón de baloncesto oficial de la NBA, talla 7',
                'precio' => 29.99,
                'unidades' => 40,
                'imagen' => 'balon_baloncesto.jpg',
                'categoria_id' => '3',
            ],
            [
                'nombre' => 'Raqueta de Tenis Wilson',
                'descripcion' => 'Raqueta de tenis para adultos con tecnología BLX',
                'precio' => 89.99,
                'unidades' => 20,
                'imagen' => 'raqueta_tenis.jpg',
                'categoria_id' => '3',
            ],
            [
                'nombre' => 'Kuki',
                'descripcion' => 'El mejor perro del mundo comiéndose un churro',
                'precio' => 9999.99,
                'unidades' =>1,
                'imagen' => 'kuki.jpg',
                'categoria_id' => '6',
            ],
            [
                'nombre' => 'Kuki Sentao',
                'descripcion' => 'El mejor perro del mundo sentao',
                'precio' => 9999.99,
                'unidades' =>1,
                'imagen' => 'kuki_sentao.jpg',
                'categoria_id' => '6',
            ],
            [
                'nombre' => 'Juguete de Cerdo',
                'descripcion' => 'Juguete de cerdo para perros',
                'precio' => 9.99,
                'unidades' => 50,
                'imagen' => 'cerdo.jpg',
                'categoria_id' => '5',
            ],
            [
                'nombre' => 'Don Quijote de la Mancha',
                'descripcion' => 'Don Quijote de la Mancha, edición ilustrada',
                'precio' => 19.99,
                'unidades' => 30,
                'imagen' => 'quijote.jpg',
                'categoria_id' => '7',
            ],
            [
                'nombre' => 'Disco Slipknot 1º Álbum',
                'descripcion' => 'Disco de vinilo del primer álbum de Slipknot',
                'precio' => 29.99,
                'unidades' => 20,
                'imagen' => 'slipknot.jpg',
                'categoria_id' => '8',
            ],
            [
                'nombre' => 'DVD Fight Club',
                'descripcion' => 'Película en DVD de Fight Club',
                'precio' => 9.99,
                'unidades' => 40,
                'imagen' => 'fight_club.jpg',
                'categoria_id' => '9',
            ],
            [
                'nombre' => 'Halo 3 para Xbox 360',
                'descripcion' => 'Videojuego Halo 3 para Xbox 360',
                'precio' => 14.99,
                'unidades' => 30,
                'imagen' => 'halo3.png',
                'categoria_id' => '10',
            ]


            
        ];


        foreach ($productos as $producto) {
            Producto::create($producto);
        }

      
    }
}
